### ISSUE TITLE
Improve test-coverage

### ISSUE THREAD

**Issue by srisankethu** [dfarrell07/puppet-opendaylight#116]
@dfarrell07 The test-coverage is around 78% currently. It is important to achieve 100% test coverage since we trying to achieve continuous delivery.

**Comment by dfarrell07** [comment]
@srisankethu, yeah, it has slipped due to recent changes without tests. Big +1 to fixing it. :)

**Comment by srisankethu** [comment]
I will be on it :) Should I put it as a part of the project?

**Comment by dfarrell07** [comment]
> Should I put it as a part of the project?

Sure, can definitely be be scoped under Int/Pack's intern project.
