### ISSUE TITLE
Update Ruby/Puppet versions

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/puppet-opendaylight#119]
Travis CI [builds with Ruby 2.0.0 are failing](https://travis-ci.org/dfarrell07/puppet-opendaylight/builds/183731333) because a dependent gem now requires ruby>=2.1.0. Need to update versions of Ruby we test. Also very likely will need to update Puppet versions as we make these changes. [See the .travis.yml file](https://github.com/dfarrell07/puppet-opendaylight/blob/master/.travis.yml#L11).

**Comment by dfarrell07** [comment]
I have a start at this here: https://github.com/dfarrell07/puppet-opendaylight/commit/58fd3bfdd4be4f3c24679d57ca7bb7a4e4f2d833

**Comment by dfarrell07** [comment]
This is another example of why we need periodic checks - things change under us and break us.

https://trello.com/c/siVk3ioH/384-periodic-test-job-for-puppet-rspec
https://trello.com/c/v1xywLZT/390-periodic-test-job-for-puppet-beaker

**Comment by srisankethu** [comment]
@dfarrell07 I have subscribed to the trello cards. I will work on them once I am done with coala and packer tasks 👍

**Comment by dfarrell07** [comment]
@srisankethu Awesome, thanks :100:
