### ISSUE TITLE
Fix how java options are set in systemd unit file

### ISSUE THREAD

**Issue by trozet** [dfarrell07/puppet-opendaylight#139]
Currently we use _JAVA_OPTIONS to set extra cmd line java arguments.  This method doesn't seem to work well with multiple arguments, and if setting options that karaf.sh will also set by default, ODL wont start.  karaf.sh checks for "JAVA_OPTS" environment variable to override default java options.  We should modify the way we configure java options to use that variable, so that a user can be explicit and deterministic in getting the exact java options he/she wants.

**Comment by dfarrell07** [comment]
This repo moved to OpenDaylight's infra and the issue tracking moved to OpenDaylight's Jira. The new issue to track this is: https://jira.opendaylight.org/browse/INTPAK-117
