### ISSUE TITLE
Add param to configure log level

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/puppet-opendaylight#42]
The folks consuming this mod in context of OpenDaylight+OpenStack need a way to set the verbosity of ODL's log output, for better debugging.

**Comment by dfarrell07** [comment]
The only way I currently know how to change the log level is directly in the Karaf shell. [Here's an example from WCBench](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L745-L760):

```
    # Change log level to ERROR
    # Loop until exit status 0 (success) given by Karaf shell
    # Exit status 255 means Karaf shell isn't open for SSH connections yet
    if "$VERBOSE" = true; then
        until sshpass -p karaf ssh -p $KARAF_SHELL_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no karaf@localhost log:set ERROR
        do
            echo "Karaf shell isn't ready yet, sleeping 5 seconds..."
            sleep 5
        done
    else
        until sshpass -p karaf ssh -p $KARAF_SHELL_PORT -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no karaf@localhost log:set ERROR &> /dev/null
        do
            sleep 5
        done
    fi
    echo "Issued \`log:set ERROR\` command via Karaf shell to localhost:$KARAF_SHELL_PORT"
```

While I think it's *possible* to do that via Puppet, it would be much more elegant to do it by modifying a config file or similar.

**Comment by trozet** [comment]
You can actually set the config in /opt/opendaylight-0.2.2/etc/org.ops4j.pax.logging.cfg.  My hack below is ugly, but it works.  Maybe you could do some template magic to add logs.

file {'/opt/opendaylight-0.2.2/etc/org.ops4j.pax.logging.cfg':
    ensure  => file,
    content => '# Root logger
log4j.rootLogger=INFO, out, osgi:*
log4j.throwableRenderer=org.apache.log4j.OsgiThrowableRenderer

# CONSOLE appender not used by default
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} | %-5.5p | %-16.16t | %-32.32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n

# File appender
log4j.appender.out=org.apache.log4j.RollingFileAppender
log4j.appender.out.layout=org.apache.log4j.PatternLayout
log4j.appender.out.layout.ConversionPattern=%d{ISO8601} | %-5.5p | %-16.16t | %-32.32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n
log4j.appender.out.file=${karaf.data}/log/karaf.log
log4j.appender.out.append=true
log4j.appender.out.maxFileSize=1MB
log4j.appender.out.maxBackupIndex=10

# Sift appender
log4j.appender.sift=org.apache.log4j.sift.MDCSiftingAppender
log4j.appender.sift.key=bundle.name
log4j.appender.sift.default=karaf
log4j.appender.sift.appender=org.apache.log4j.FileAppender
log4j.appender.sift.appender.layout=org.apache.log4j.PatternLayout
log4j.appender.sift.appender.layout.ConversionPattern=%d{ISO8601} | %-5.5p | %-16.16t | %-32.32c{1} | %m%n
log4j.appender.sift.appender.file=${karaf.data}/log/$\\{bundle.name\\}.log
log4j.appender.sift.appender.append=true

log4j.logger.org.opendaylight.ovsdb = TRACE
log4j.logger.org.opendaylight.ovsdb.lib = INFO
log4j.logger.org.opendaylight.ovsdb.openstack.netvirt.impl.TenantNetworkManagerImpl = DEBUG
log4j.logger.org.opendaylight.ovsdb.plugin.md.OvsdbInventoryManager = INFO
log4j.logger.org.opendaylight..controller.networkconfig.neutron = TRACE',
  }

**Comment by dfarrell07** [comment]
> You can actually set the config in /opt/opendaylight-0.2.2/etc/org.ops4j.pax.logging.cfg.

Awesome! Saved me some effort digging this up. :+1: 

> log4j.rootLogger=INFO

So this is the line that would change all the log levels, if I'm parsing this correctly.

**Comment by shague** [comment]
It would be best to allow setting the individual components log level. log4j.rootLogger is the default for all the components so that would be very noisy.
In Tim's example is what we would want. ovsdb is set at TRACE for the whole ovsdb component, then we fine tune it and lower ovsdb.lib to INFO - because the lib is very noisy and not useful.

**Comment by dfarrell07** [comment]
6c1cca8114e418317cd34b129d28b4d17a708d76 added a new `log_levels` param.
53bc9a8317ce84c71ee31298f83e55927e9e3a73 added rspec-puppet tests for the new param.
5b0c75286b2784d1aa1a1bac99d2affdf29a3dcf added Beaker tests for the new param.
d88045ff2f7d59336f18d5883e0404d9a77c6fed added docs for the new param.

[This vagrant-opendaylight box](https://github.com/dfarrell07/vagrant-opendaylight/blob/f8326fb8aa9b1b16f3d2ad9cac94e22daf95d447/Vagrantfile#L150-L166) uses the new params ([manifest here](https://github.com/dfarrell07/vagrant-opendaylight/blob/f8326fb8aa9b1b16f3d2ad9cac94e22daf95d447/manifests/custom_loggers.pp)) to configure OVSDB's logging as @shague described above.

All rspec-puppet and Beaker tests are passing. The vagrant-opendaylight box seems to work as expected under manual inspection. Closing this as done.
