### ISSUE TITLE
Upstart ODL service failing for Ubuntu 14.04

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/puppet-opendaylight#72]
After PR #69 added initial Ubuntu 14.04 support, I added rspec-puppet test coverage in #70 and Beaker test coverage in #71. I fixed a bunch of issues along the way, and will continue fixing the remaining ones, but it'd be awesome to get some help with this Upstart failure. I don't know much about Upstart (systemd, yes) and would prefer not to spin-up on it to fix this.

To reproduce, use the new `bundle exec rake ubuntu` rake task. Relevant parts of output:

```
[~/puppet-opendaylight]$ BEAKER_destroy=no bundle exec rake ubuntu &> ubuntu0.log
RS_SET=ubuntu-1404 INSTALL_METHOD=tarball bundle exec rake beaker
# snip    Service "opendaylight"
    Service "opendaylight"

ubuntu-1404 15:51:29$ /bin/sh -c ls\ /etc/rc3.d/\ \|\ grep\ --\ \'\^S..opendaylight\'\ \|\|\ grep\ \'start\ on\'\ /etc/init/opendaylight.conf

ubuntu-1404 executed in 0.04 seconds
Exited: 1
      should be enabled (FAILED - 4)
      should be enabled (FAILED - 4)

ubuntu-1404 15:51:29$ /bin/sh -c ls\ /etc/rc3.d/\ \|\ grep\ --\ \'\^S..opendaylight\'\ \|\|\ grep\ \'start\ on\'\ /etc/init/opendaylight.conf

ubuntu-1404 executed in 0.04 seconds
Exited: 1
      should be enabled (FAILED - 5)
      should be enabled (FAILED - 5)

ubuntu-1404 15:51:29$ /bin/sh -c service\ opendaylight\ status\ \&\&\ service\ opendaylight\ status\ \|\ grep\ \'running\'
status: Unknown job: opendaylight

ubuntu-1404 executed in 0.04 seconds
Exited: 1

ubuntu-1404 15:51:29$ /bin/sh -c ps\ aux\ \|\ grep\ -w\ --\ opendaylight\ \|\ grep\ -qv\ grep

ubuntu-1404 executed in 0.04 seconds
Exited: 1
      should be running (FAILED - 6)
      should be running (FAILED - 6)
# snip
    Process "java"
    Process "java"

ubuntu-1404 15:51:29$ /bin/sh -c ps\ -C\ java\ -o\ pid\=\ \|\ head\ -1

ubuntu-1404 executed in 0.04 seconds
      should be running (FAILED - 7)
      should be running (FAILED - 7)
    File "/etc/init/opendaylight.conf"
    File "/etc/init/opendaylight.conf"
# snip
Finished in 7 minutes 8 seconds (files took 1 minute 11.79 seconds to load)
51 examples, 15 failures

Failed examples:
# snip
rspec ./spec/acceptance/class_spec.rb:11 # opendaylight class testing install methods Service "opendaylight" should be enabled
rspec ./spec/acceptance/class_spec.rb:11 # opendaylight class testing install methods Service "opendaylight" should be enabled
rspec ./spec/acceptance/class_spec.rb:11 # opendaylight class testing install methods Service "opendaylight" should be running
rspec ./spec/acceptance/class_spec.rb:11 # opendaylight class testing install methods Process "java" should be running
```

You can also connect to the built box like this.

```
[~/puppet-opendaylight]$ cd .vagrant/beaker_vagrant_files/ubuntu-1404.yml
[~/puppet-opendaylight/.vagrant/beaker_vagrant_files/ubuntu-1404.yml]$ vagrant ssh
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-30-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Wed Mar 25 12:47:14 2015 from 10.0.2.2
vagrant@ubuntu-1404:~$ ls -l /opt/
total 8
drwxr-xr-x 10 odl  odl  4096 Mar 25 12:54 opendaylight
drwxr-xr-x  9 root root 4096 Feb 25 07:41 VBoxGuestAdditions-4.3.22
vagrant@ubuntu-1404:~$ ls -l /etc/init/ | grep -i opendaylight
-rw-r--r-- 1 root root   47 Mar 25 12:48 opendaylight.conf
vagrant@ubuntu-1404:~$ pgrep java
vagrant@ubuntu-1404:~$ sudo service opendaylight status
status: Unknown job: opendaylight
vagrant@ubuntu-1404:~$ logout
Connection to 127.0.0.1 closed.
[~/puppet-opendaylight/.vagrant/beaker_vagrant_files/ubuntu-1404.yml]$ vagrant destroy -f
==> ubuntu-1404: Forcing shutdown of VM...
==> ubuntu-1404: Destroying VM and associated drives...
[~/puppet-opendaylight/.vagrant/beaker_vagrant_files/ubuntu-1404.yml]$ cd ..
[~/puppet-opendaylight/.vagrant/beaker_vagrant_files]$ rm -rf ubuntu-1404.yml
```

**Comment by dfarrell07** [comment]
I cleaned up some other (more minor) Beaker test issues, so all of the failures when running against Ubuntu are now related to this Upstart bug.

Changes to files via `puppet apply`s

```
        Notice: /Stage[main]/Opendaylight::Config/File[org.apache.karaf.features.cfg]/g
roup: group changed 'root' to 'odl'
```

Cause service refreshes

```
        Info: Class[Opendaylight::Config]: Scheduling refresh of Class[Opendaylight::Se
rvice]
        Info: Class[Opendaylight::Service]: Scheduling refresh of Service[opendaylight]
```

Which fail with the error [described in detail above](https://github.com/dfarrell07/puppet-opendaylight/issues/72#issue-64364196)

```
        Error: /Stage[main]/Opendaylight::Service/Service[opendaylight]: Could not eval
uate: Execution of '/sbin/status opendaylight' returned 1: status: Unknown job: openday
light
```

**Comment by davidblaisonneau-orange** [comment]
Hi Daniel,

my bad, I forgot some changes in my 2nd PR:
* the template
* an error in the content value for the upstart file.

Do you prefer a new PR or just the diff in a gist ?

**Comment by dfarrell07** [comment]
Hey David! Thanks for following up. :)

> Do you prefer a new PR or just the diff in a gist ?

A new PR would be ideal.

**Comment by dfarrell07** [comment]
> the template

I'm not sure what template you mean, but note that I moved your [Upstart conf file](https://github.com/dfarrell07/puppet-opendaylight/blob/master/files/upstart.odl.conf) from a `template` type to a `file` type, because its content isn't dynamic.

**Comment by davidblaisonneau-orange** [comment]
Ok, it's true, there is no more vars in the file. Just replace 'content' by 'source' line 150 of install.pp and it should be OK.

**Comment by dfarrell07** [comment]
> Just replace 'content' by 'source' line 150 of install.pp and it should be OK.

I'm almost sure that `content` with the `file` helper will have the exact same effect as `source`, but I'm currently testing to confirm.

I'm fairly sure that the problem is with the Upstart config file itself, not Puppet's handling of it. Manually inspecting Ubuntu systems provisioned by the mod, the config file is there and contains the expected content. But, [as described above](https://github.com/dfarrell07/puppet-opendaylight/issues/72#issue-64364196), it doesn't seem to correctly manage the ODL service. More debugging info shortly...

**Comment by davidblaisonneau-orange** [comment]
During my last install the content of the upstart file was "puppet:///.....". that was why it was not working

**Comment by dfarrell07** [comment]
```
49 examples, 0 failures
```

Huzzah!

> Just replace 'content' by 'source' line 150 of install.pp and it should be OK.
>> I'm almost sure that content with the file helper will have the exact same effect as source, but I'm currently testing to confirm.

Yeah, you were totally right! Awesome, we now have fully solid Ubuntu 14.04 support! Thanks *tons* @davidblaisonneau-orange, you rock! :D

**Comment by dfarrell07** [comment]
> I'm almost sure that content with the file helper will have the exact same effect as source, but I'm currently testing to confirm.

For the record, I wasn't actually using a `file` helper with the `content` var to load the contents, which was resulting in the "content" being the path to the file, not the contents of the file.
