### ISSUE TITLE
problem running dlux, l2 learning switch

### ISSUE THREAD

**Issue by hdb3** [dfarrell07/puppet-opendaylight#75]
Hi
I've used the latest commit (29c6e386c2e614d719d8c09e32b183248943515b).
Running on a clean Centos7.
Created a very simple odl.pp and applied it:
```
class { 'opendaylight':
  extra_features => ['odl-restconf','odl-l2switch-switch','odl-mdsal-apidocs','odl-dlux-core'],
}
```
Result: ODL is running (a lot of TCP sockets opened by java, including 8181, which is the DLUX UI).
But: opening http://<myip>:8181/dlux/index.html gives a login panel which doesn't accept the usual admin/admin credentials, and the karaf log is full of interesting but not good stuff.  See on dropbox: https://www.dropbox.com/s/9hx60bowmdlr1x7/karaf.log.gz?dl=0

Also, I cannot open a karaf console: /opt/opendaylight/bin/karaf just hangs after saying 'OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0'

Questions: how to login to karaf/ODL console?; what ODL app did you test?; did I miss anything out in my install process (I just sym-linked the source directory puppet-opendaylight into /etc/puppet/modules as opendaylight)?

thanks and brgds

nic

**Comment by dfarrell07** [comment]
This may be related to #76. I should have that fixed in the next few minutes.

**Comment by hdb3** [comment]
I've repeated the exact same operations as described previously, and I obtain a working installation (not rigorously tested, but not at all broken as described previously.)  Yes, I don't believe it's exactly the same.  Only difference I can pinpoint (and I don't believe is relevant): in first case my VM was running in a large OpenStack system, this time it's a much smaller machine (under VMware).

BTW, the Java version installed (by puppet..) is OpenJDK 1.7.0_79...

I'd still like to know, however, how to run a local karaf console....

**Comment by dfarrell07** [comment]
> I'd still like to know, however, how to run a local karaf console....

Sorry, almost missed this.

I think you're asking to connect to the Karaf shell. Just SSH to it with something like `ssh -p 8101 karaf@localhost`. To get more fancy, check out this [`connect.sh`](https://github.com/dfarrell07/vagrant-opendaylight/blob/master/scripts/connect.sh) script.

**Comment by hdb3** [comment]
Thanks Daniel - that is exactly my question.

Can I suggest that it would be helpful to include this in the README on 
github?

nic

**Comment by dfarrell07** [comment]
> Can I suggest that it would be helpful to include this in the README on github?

Sure, sounds like a good addition. Thanks for the suggestion.

**Comment by dfarrell07** [comment]
@hdb3 - Raised #80 to track that docs update.
