### ISSUE TITLE
Lithium Support

### ISSUE THREAD

**Issue by trozet** [dfarrell07/puppet-opendaylight#82]
Templates used in the puppet module need to be changed to support Lithium.  See:
https://github.com/trozet/puppet-opendaylight/commit/5843bcf82bf8b84fc13b744d86bbc3f540cb71de

Also the tomcat template may have changed.  Have not done a diff of it yet.

Also the build and repo locations need to change in the puppet module to point to lithium.  Maybe have an argument for lithium as the default, but backwards compatibility you can provide "release => helium".

**Comment by dfarrell07** [comment]
> Maybe have an argument for lithium as the default, but backwards compatibility you can provide "release => helium".

I think we'll have to let versioning handle providing backwards compatibility for those who need it, with HEAD of master pointing at whatever the latest release is.

+1 to the rest of it, I'll try to get this done today.

**Comment by trozet** [comment]
rest port has to be changed in jetty.xml file rather than tomcat.  See this change:
https://github.com/trozet/puppet-opendaylight/commit/b696a63e9f57b459cca0d96979476148666ac1ae

**Comment by dfarrell07** [comment]
This may be a little harder than I was anticipating.

When I build a new Lithium RPM on Copr, the Helium one will stop being accessible, including for versions of the Puppet mod that should have backwards compatibility with Helium.

We need to serve up all RPM versions to avoid issues like this. Thinking about the best way to do that now (ODL infra, CentOS NFV SIG, etc).

**Comment by dfarrell07** [comment]
> When I build a new Lithium RPM on Copr, the Helium one will stop being accessible, including for versions of the Puppet mod that should have backwards compatibility with Helium.

This wasn't an issue before because the project wasn't mature enough to offer any assurance of backwards compatibility. We've since tagged 1.0.0 and are being consumed by OPNFV, so we've made backwards compatibility commitments.

**Comment by trozet** [comment]
This is probably a great time as you mentioned to move RPM to ODL repo or CentOS, if possible.

**Comment by dfarrell07** [comment]
> This is probably a great time as you mentioned to move RPM to ODL repo or CentOS, if possible.

+1

That does imply that adding Lithium support to the Puppet mod (this issue) is going to be delayed.

**Comment by dfarrell07** [comment]
The Lithium RPM is now [up on Koji](http://cbs.centos.org/repos/nfv7-opendaylight-3-candidate/x86_64/os/Packages/), so this is un-blocked.

**Comment by dfarrell07** [comment]
9a5cf04edd5ea35682e4d20a2f2a5f01d1ed61b2 add initial support for Lithium and the CBS repo.

**Comment by dfarrell07** [comment]
206cb0cdf6b048f94e41dc5f94676eac432c8cc8, 49a1f087e55d2f5cb810f8f1c4d9bd79f9190cc6 and e9f0b96b61de888a544f020f5c35935689476b8a added the rest of the Lithium upgrade.

**Comment by dfarrell07** [comment]
@trozet - I think this is done. If you can pull it into your system and verify, I'll tag it as a release. Thanks!
